name: aae497-f19
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - matplotlib
  - numpy
  - scipy
  - control
  - pydot
  - autopep8
  - pytest=5.0.1
  - jupyterlab
  - ffmpeg
  - openh264
  - pandas
  - pip:
    - casadi
